config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'homes#dashboard'
   resources :homes, only: [] do
    collection do
      get 'about_us'
      get 'contact_us'
      get 'dashboard'
      get 'guest_user'
      get 'app_user'
      get 'server_error'
      post 'contact_mail'
    end
  end

  resources :images do
    collection do
      get 'validate_uniqueness'
      post 'update_title'
      get 'image_count'
    end
  end

 namespace :api do
  namespace :v1 do
    resources :users, only: [:create]
    resources :images, only: [:create,:show]
    resources :homes, except: [:index, :new, :edit, :update,:show,:destroy] do
       collection do
          post 'contact_mail'
       end
    end

  end
end

  mount Sidekiq::Web => '/sidekiq'
  # Handle unmatched routes
  get '*unmatched_route', to: 'homes#server_error'
  post '*unmatched_route', to: 'api/v1/homes#server_error'

end

app/controllers/api/v1/homes_controller.rb
class Api::V1::HomesController < ApiApplicationController
 before_filter :autenticate_user,only: [:contact_mail]

    # http://0.0.0.0:4000/api/v1/homes/contact_mail.json?
	def contact_mail
	  begin
	    message,status = request_params_validator contact_params, "contact"
		return message if status === true
	    contact_mail_info={name: contact_params[:name] , phone_number: contact_params[:phone],
	    	email: contact_params[:email] , description: contact_params[:description],type: "contact" }
        BackgroundWorker.perform_async contact_mail_info

		return render_message({status:SUCCESS_STATUS,responseMessage: "Thanks for submitting your request. Someone will get back to you in 48hrs.",
		 responseCode: SUCCESS})
		rescue Exception => e
		   return render_message({status:ERR_STATUS,responseMessage: "Something went wrong! Please try again later!",
			 responseCode: ERROR})
	  end
	end

    def server_error
	  respond_to do |format|
	     format.json { render :json => {status:SUCCESS_STATUS, :response_message => NO_ROUTE_MESSAGE, :response_code => NO_ROUTE} }
	    format.html {  }
	  end
    end

    private
    def contact_params
      params.permit(:name,:email,:phone,:description)
   end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    before_action :authenticate_user!, :except => [:dashboard,:guest_user,:server_error]

    def dashboard;end

	def about_us;end

	def contact_us;end

	def guest_user;end

    def app_user;end

    def server_error
	 	respond_to do |format|
	      format.json { render :json => { :response_code => NO_ROUTE, :response_message => NO_ROUTE_MESSAGE} }
	      format.html {  }
	    end
    end

    def contact_mail
	  begin
	    return redirect_to :back  unless params[:c_name].present? && params[:c_email].present? && params[:c_phone].present? && params[:c_description].present?
	    contact_mail_info={name: params[:c_name] , phone_number: params[:c_phone], email: params[:c_email] , description: params[:c_description],type: "contact" }
        BackgroundWorker.perform_async contact_mail_info
		flash[:notice]= "Thanks for submitting your request. Someone will get back to you in 48hrs."
	    redirect_to dashboard_homes_path
	  rescue Exception => e
			flash[:notice]= "Something went wrong! Please try again later!"
		    redirect_to dashboard_homes_path
	  end
	end

end

app/helpers/api/v1/homes_helper.rb
module Api::V1::HomesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
  def contact_helper
	current_user  ? (link_to "Contact Us", {controller: "/homes", action: "contact_us"}, class: "contact-us-link")  : "Contact Us"
  end
end

app/views/homes/about_us.html.haml
.row.about-us-content
  .col-md-12
    .well.well-sm
      %fieldset
        %center
          %h2
            About Maropost
          .thumbnail.text-center
            = image_tag "/assets/maropost.png", height:"500" , width: "1100", class: "img-responsive"
            .col-text.caption
              %p The world's best enterprise platform
              %p Maropost is the last sales and marketing solution you'll ever need
        .col-sm-12.abt-content
          %p
            Maropost is the leading global provider of on-demand marketing, sales, commerce, and infrastructure solutions. We offer the world’s best marketing and sales cloud platforms combined with industry leading customer support and client success.
          %p
            From web, to mobile, to social, and across email, SMS, and digital, our Marketing Cloud offers the industry’s most advanced personalization and automation features – all to make your life easier and to increase your marketing ROI.
          %p
            Maropost was founded in 2011 by CEO and Chairman Ross Andrew Paquette. We are headquartered in Toronto, Canada, with offices in New York, USA, London, U.K., and Chandigarh, India.
          %p
            Maropost Sales Cloud is the all-in-one platform for your sales, customer service, and commerce departments. Our Sales Cloud was built from the ground up to offer combined insight and complete integration for a 360 business view. With our first-class customer support, we’ve built the last sales platform you’ll ever use. And the best part? You can choose and customize what features you want. Because the challenges your business is facing are unique, and you need a tailored solution for maximum success.
        .wrap-why
          %h2 Why Maropost
          %p We help modern marketing and sales teams scale up their digital audience, engagement, and revenue to new heights by delivering 2 imperative things: an innovative product, and an excellent service experience.
          .row
            .col-sm-12.col-md-4
              %h3 High Performance
              %p Our product teams push weekly updates of features designed to make sales and marketing professionals lives easier, and to keep us moving as fast as our leading edge customers.
            .col-sm-12.col-md-4
              %h3 Enterprise Scale
              %p We're built for enterprise scale without the enterprise bloat. That's why we're the enterprise of choice for lean sales and marketing teams growing large digital audiences.
            .col-sm-12.col-md-4
              %h3 High Touch Service
              %p In an age of scaling back or automating customer service, we're going all in. At your service with 24/7 Talk-to-a-human support via email, phone, or live-chat.

app/views/homes/app_user.html.haml
.row
  .col-md-6.col-md-offset-3
    .well.well-sm
      %fieldset
        .form-group
          .col-md-12.user-email
            Welcome #{current_user.email}
        .form-group
          .col-md-12
            Thanks for subscribing with us!
        .form-group
          .col-md-12
            You can explore Gallery  by clicking
            \#{link_to "Gallery", images_path, :class => 'gallery-link btn btn-success'}

app/views/homes/contact_us.html.haml
.row
  .col-md-12
    .col-md-6
      .well.well-sm
        = form_for :new,url: contact_mail_homes_path , html: {:id => 'contact_us', class: "form-horizontal" } do |f|
          %fieldset
            %legend.text-center Contact us
            / Name input
            .form-group
              %label.col-md-3.control-label Name
              .col-md-9
                %input.form-control{:maxlength => "20", :name => "c_name", :placeholder => "Name", :type => "text"}/
            / Email input
            .form-group
              %label.col-md-3.control-label Email
              .col-md-9
                %input.form-control{:maxlength => "64", :name => "c_email", :placeholder => "Email", :type => "email"}/
            / Phone number input
            .form-group
              %label.col-md-3.control-label Phone number
              .col-md-9
                %input.form-control{:maxlength => "12", :name => "c_phone", :placeholder => "Phone number", :type => "text"}/
            / Description body
            .form-group
              %label.col-md-3.control-label Description
              .col-md-9
                %textarea.form-control{:maxlength => "500", :name => "c_description", :placeholder => "Please enter your message here...", :rows => "5"}
            / Form actions
            .form-group
              .col-md-12.text-right
                %button.btn.btn-primary.btn-lg{:type => "submit"} Submit
    .col-md-6
      .well.well-sm
        %iframe{:allowfullscreen => "", :frameborder => "0", :height => "400", :src => "https://www.google.com/maps/embed/v1/place?key=AIzaSyDBvzq5WsidARhAZ0821MB1iAMTPnHiamI&q=155 University Ave Suite 1900, Toronto, ON M5H 3B7, Canada", :style => "border:0", :width => "500"}

app/views/homes/dashboard.html.haml
- if current_user
  = render template: 'homes/app_user'
- else
  = render template: 'homes/guest_user'

app/views/homes/guest_user.html.haml
.inner-container.guest-inner
  .col-md-12
    .guest_dashboard.text-center
      = link_to "Sign up", new_user_registration_path, :class => 'btn btn-primary xlarge button'
      = link_to "Login", new_user_session_path, :class => 'btn btn-primary xlarge button'
  .col-md-12.text-center
    = link_to "Forget password", new_user_password_path, :class => 'btn btn-primary xlarge button'

app/views/homes/server_error.html.haml
.row
  .col-md-6.col-md-offset-3
    .well.well-sm
      %fieldset
        .form-group
          Sorry, we can’t seem to find the page you were looking for.
        .form-group
          If you would like to return to your main dashboard click #{link_to "here", root_path}.
        - if current_user
          .form-group
            Our team have been informed about this error and will look into it as a top priority. But if the problem persists, please feel free to #{link_to "contact us", contact_us_homes_path}