config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'homes#dashboard'
   resources :homes, only: [] do
    collection do
      get 'about_us'
      get 'contact_us'
      get 'dashboard'
      get 'guest_user'
      get 'app_user'
      get 'server_error'
      post 'contact_mail'
    end
  end

  resources :images do
    collection do
      get 'validate_uniqueness'
      post 'update_title'
      get 'image_count'
    end
  end

 namespace :api do
  namespace :v1 do
    resources :users, only: [:create]
    resources :images, only: [:create,:show]
    resources :homes, except: [:index, :new, :edit, :update,:show,:destroy] do
       collection do
          post 'contact_mail'
       end
    end

  end
end

  mount Sidekiq::Web => '/sidekiq'
  # Handle unmatched routes
  get '*unmatched_route', to: 'homes#server_error'
  post '*unmatched_route', to: 'api/v1/homes#server_error'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DemoApp
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render template: "layouts/header"
    .container
      - flash.each do |key, val|
        .alert.alert-info.alert-dismissable
          %a.close{"aria-label" => "close", "data-dismiss" => "alert", :href => "#"} ×
          = val
      = yield
    = render template: "layouts/footer"

app/views/layouts/footer.html.haml
%footer.navbar-default.navbar-fixed-bottom.footer-res
  .container-fluid
    %span.pull-left
      © 2017 Maropost Inc. All rights reserved. |  #{contact_helper}

app/views/layouts/header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .navbar-header
    %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{:href => "/"} Demo Project
  #navbar.navbar-collapse.collapse{"aria-expanded" => "false", :style => "height: 1px;"}
    - if current_user
      %ul.nav.navbar-nav
        %li
          = link_to "About us", about_us_homes_path, :class => 'about-us-link'
        %li
          = link_to "Contact us", contact_us_homes_path, :class => 'contact-us-link'
        %li
          = link_to "Gallery", images_path, :class => 'gallery-link'
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a.dropdown-toggle.action-link{"data-toggle" => "dropdown", :href => "#"}
            %span.glyphicon.glyphicon-user
            = current_user.try(:email)
            %span.glyphicon.glyphicon-chevron-down
          %ul.dropdown-menu
            %li
              = link_to "Update Password", edit_user_registration_path, :class => 'update-profile'
              = link_to "Logout", destroy_user_session_path, method: :delete, :class => 'logout-link'

      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a.dropdown-toggle.action-link{"data-toggle" => "dropdown", :href => "#"}
            %span.glyphicon.glyphicon-bell
            %span Upload notification
          %ul.dropdown-menu
            %li
              %span.success-count Success #{$redis.get("success_count")}
              %span.error-count Error  #{$redis.get("error_count")}